# -*- coding: utf-8 -*-
"""Untitled98.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17559Mc6loxsqyuupvigsDowWiUS6pow_
"""

import streamlit as st
import base64
import joblib
import re
import string
from PyPDF2 import PdfReader

from utils.text_cleaner import clean_text
from utils.chatbot_logic import init_chat, handle_input
from modules.roadmap_generator import generate_career_roadmap as generate_roadmap
from modules.skill_gap import detect_skill_gap
from modules.domain_detector import detect_domain, domain_skills
from modules.skill_extractor import extract_skills
from modules.career_reasoner import reason_career
from modules.resume_parser import parse_resume

# 1. Page Configuration
st.set_page_config(page_title="Career Agent | NR Solution", layout="wide")


# --- Helper: Load career brain ---
@st.cache_resource
def load_career_brain():
    try:
        return joblib.load('career_brain.pkl')
    except:
        return None

career_brain = load_career_brain()
embedding_model = load_career_brain()  # If embedding_model is also a joblib file
label_encoder = load_career_brain()    # If label_encoder is also a joblib file


# --- LOAD KNOWLEDGE BASE ---
import json
with open("data/kb.json", "r") as f:
    KB = json.load(f)
with open("data/role_keyword.json", "r") as f:
    ROLE_KEYWORDS = json.load(f)


# --- SESSION STATE ---
if 'page' not in st.session_state:
    st.session_state.page = 'home'
if 'messages' not in st.session_state:
    st.session_state.messages = {}


# --- HELPER: Load local logo ---
def get_base64_of_bin_file(bin_file):
    try:
        with open(bin_file, 'rb') as f:
            data = f.read()
        return base64.b64encode(data).decode()
    except:
        return None

logo_base64 = get_base64_of_bin_file('logo.png')
logo_url = f"data:image/png;base64,{logo_base64}" if logo_base64 else "https://cdn-icons-png.flaticon.com/512/3135/3135715.png"


# --- CUSTOM CSS ---
st.markdown(f"""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&family=Inter:wght@400;700&display=swap');
    .stApp {{ background-color: #ffffff; }}
    * {{ font-family: 'Inter', sans-serif; }}

    .logo-img {{ height: 60px; width: auto; border-radius: 10px; object-fit: contain; }}
    .brand-text {{ margin-left: 15px; font-weight: 800; font-size: 1.8rem; color: #1e3a8a; font-family: 'Poppins'; }}

    .sector-card {{
        padding: 40px 20px; border-radius: 25px; text-align: center; color: white;
        height: 250px; display: flex; flex-direction: column; justify-content: center; border: 4px solid white;
        box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);
    }}
    .bg-govt {{ background: linear-gradient(45deg, #f093fb, #f5576c); }}
    .bg-med {{ background: linear-gradient(45deg, #5ee7df, #b490ca); }}
    .bg-nr {{ background: linear-gradient(45deg, #2af598, #009efd); }}
    .bg-it {{ background: linear-gradient(45deg, #667eea, #764ba2); }}
    .bg-counsel {{ background: linear-gradient(45deg, #ff9a9e, #fecfef); }}
    .bg-ai {{ background: linear-gradient(45deg, #21d4fd, #b721ff); }}

    .reg-card {{
        padding: 30px 15px; border-radius: 20px; text-align: center; color: white;
        min-height: 220px; display: flex; flex-direction: column; justify-content: center;
        margin-bottom: 10px; border: 3px solid rgba(255,255,255,0.3);
    }}
    .reg-student {{ background: linear-gradient(135deg, #6a11cb 0%, #2575fc 100%); }}
    .reg-counselor {{ background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%); }}
    .reg-company {{ background: linear-gradient(135deg, #ee0979 0%, #ff6a00 100%); }}
    .reg-college {{ background: linear-gradient(135deg, #4568dc 0%, #b06ab3 100%); }}

    .form-wrap-student {{ background-color: #f0f7ff; border-left: 10px solid #6a11cb; padding: 25px; border-radius: 15px; }}
    .form-wrap-counselor {{ background-color: #f0fff4; border-left: 10px solid #11998e; padding: 25px; border-radius: 15px; }}
    .form-wrap-company {{ background-color: #fff5f7; border-left: 10px solid #ee0979; padding: 25px; border-radius: 15px; }}
    .form-wrap-college {{ background-color: #f8f7ff; border-left: 10px solid #4568dc; padding: 25px; border-radius: 15px; }}

    .dashboard-header {{ padding: 40px; border-radius: 25px; color: white; text-align: center; margin-bottom: 30px; }}
    .info-ticker-box {{ background: #f8fafc; padding: 20px; border-radius: 20px; border: 1px solid #e2e8f0; height: 550px; overflow-y: auto; }}
    .ticker-item {{ background: white; padding: 15px; border-radius: 12px; margin-bottom: 10px; border-left: 5px solid #1e3a8a; box-shadow: 0 2px 4px rgba(0,0,0,0.05); font-size: 0.9rem; }}

    .hero-box {{ background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url('https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80'); background-size: cover; padding: 100px 20px; color: white; text-align: center; border-radius: 0 0 40px 40px; margin-bottom: 40px; }}
    .form-container {{ background: #ffffff; padding: 30px; border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); border: 1px solid #f1f5f9; }}

    /* New Stat Styling */
    .stat-box {{ background: #f8fafc; padding: 20px; border-radius: 15px; border: 1px solid #e2e8f0; text-align: center; }}
    </style>
    """, unsafe_allow_html=True)


# --- NAVIGATION HELPER ---
def go_to(page_name):
    st.session_state.page = page_name
    st.rerun()


# --- HEADER ---
header_col1, header_col2, header_col3 = st.columns([4, 4, 2])
with header_col1:
    st.markdown(
        f'<div style="display: flex; align-items: center; padding-top: 10px;">'
        f'<img src="{logo_url}" class="logo-img">'
        f'<span class="brand-text">NR SOLUTION</span></div>',
        unsafe_allow_html=True
    )

with header_col3:
    if st.button("🚀 REGISTER NOW", use_container_width=True, type="primary"):
        go_to('select_type')
    st.markdown("<hr style='margin-top:0;'>", unsafe_allow_html=True)


# --- ROUTING LOGIC ---

# 1. HOME PAGE
if st.session_state.page == 'home':
    st.markdown('''
        <div class="hero-box">
            <h1>AI CAREER AGENT</h1>
            <p style="font-size: 1.5rem; margin-bottom: 20px;">Professional Excellence</p>
            <div style="max-width: 800px; margin: 0 auto; background: rgba(255,255,255,0.1); padding: 20px; border-radius: 15px; backdrop-filter: blur(5px); border: 1px solid rgba(255,255,255,0.2);">
                <p style="font-size: 1.1rem; line-height: 1.6; margin: 0;">
                    NR Solution's AI Career Agent is an all-in-one ecosystem designed to bridge the gap between
                    talent and opportunity. Whether you are a student seeking guidance, a professional looking
                    to pivot, or an organization hunting for top-tier talent, our platform leverages
                    <b>Artificial Intelligence</b> to provide real-time career counseling, resume analysis,
                    and direct pathways to Government, Medical, and IT sectors.
                </p>
            </div>
        </div>
    ''', unsafe_allow_html=True)

    st.markdown("<h2 style='text-align: center; margin-bottom: 40px;'>Select Your Career Path</h2>", unsafe_allow_html=True)

    r1c1, r1c2, r1c3 = st.columns(3)
    with r1c1:
        st.markdown('<div class="sector-card bg-govt"><h1>🏛️</h1><h3>GOVT JOBS</h3></div>', unsafe_allow_html=True)
        if st.button("Explore Govt Jobs", key="btn_govt", use_container_width=True):
            go_to('path_govt')
    with r1c2:
        st.markdown('<div class="sector-card bg-med"><h1>🩺</h1><h3>MEDICAL</h3></div>', unsafe_allow_html=True)
        if st.button("Explore Medical", key="btn_med", use_container_width=True):
            go_to('path_med')
    with r1c3:
        st.markdown('<div class="sector-card bg-nr"><h1>✈️</h1><h3>NR AGENT</h3></div>', unsafe_allow_html=True)
        if st.button("Launch NR Agent", key="btn_nr", use_container_width=True):
            go_to('path_nr')

    st.markdown("<br>", unsafe_allow_html=True)
    r2c1, r2c2, r2c3 = st.columns(3)
    with r2c1:
        st.markdown('<div class="sector-card bg-it"><h1>💻</h1><h3>IT SECTOR</h3></div>', unsafe_allow_html=True)
        if st.button("Explore IT Sector", key="btn_it", use_container_width=True):
            go_to('path_it')
    with r2c2:
        st.markdown('<div class="sector-card bg-counsel"><h1>🧠</h1><h3>COUNSELING</h3></div>', unsafe_allow_html=True)
        if st.button("Explore Counseling", key="btn_counsel", use_container_width=True):
            go_to('path_counsel')
    with r2c3:
        st.markdown('<div class="sector-card bg-ai"><h1>🤖</h1><h3>AI RESUME ANALYZER</h3></div>', unsafe_allow_html=True)
        if st.button("Launch AI Analyzer", key="btn_ai", use_container_width=True):
            go_to('path_ai')


# 2. PATH DASHBOARDS
elif st.session_state.page.startswith('path_'):
    path_key = st.session_state.page.split('_')[1]
    meta = {
        "govt": {"title": "Government Jobs", "grad": "linear-gradient(45deg, #f093fb, #f5576c)"},
        "med": {"title": "Medical Career", "grad": "linear-gradient(45deg, #5ee7df, #b490ca)"},
        "nr": {"title": "NR Agent Network", "grad": "linear-gradient(45deg, #2af598, #009efd)"},
        "it": {"title": "IT & Tech Sector", "grad": "linear-gradient(45deg, #667eea, #764ba2)"},
        "counsel": {"title": "Career Counseling", "grad": "linear-gradient(45deg, #ff9a9e, #fecfef)"},
        "ai": {"title": "AI Resume Analyzer", "grad": "linear-gradient(45deg, #21d4fd, #b721ff)"}
    }

    if st.button("← Back to Home"):
        go_to('home')

    st.markdown(
        f'<div class="dashboard-header" style="background:{meta[path_key]["grad"]}">'
        f'<h1>{meta[path_key]["title"]} Hub</h1></div>', unsafe_allow_html=True
    )

    col_bot, col_info = st.columns([2, 1])
    with col_bot:
        if path_key == "ai":

            st.markdown("""
            <div style='background:linear-gradient(90deg,#4facfe,#00f2fe);
            padding:25px;border-radius:15px;color:white;
            font-size:28px;text-align:center;font-weight:bold'>
            🤖 AI Career Analyzer Dashboard
            </div>
            """, unsafe_allow_html=True)


            tab1, tab2, tab3, tab4 = st.tabs([
                "📄 Resume Analyzer",
                "📊 Skill Gap Analysis",
                "🧭 Career Path",
                "💬 AI Career Chatbot"
            ])


            uploaded_file = None
            skills = []
            missing_skills = []
            domain = ""


        # =====================================================
        # TAB 1 : RESUME ANALYZER
        # =====================================================

            with tab1:

                st.subheader("📥 Try Sample Resumes")

                col1, col2, col3, col4 = st.columns(4)

                with col1:
                    try:
                        st.download_button(
                            "Data Analyst Resume",
                            open("samples/data_analyst_resume.pdf","rb"),
                            file_name="data_analyst_resume.pdf"
                        )
                    except:
                        st.info("Sample missing")

                with col2:
                    try:
                        st.download_button(
                            "AI Engineer Resume",
                            open("samples/ai_engineer_resume.pdf","rb"),
                            file_name="ai_engineer_resume.pdf"
                        )
                    except:
                        st.info("Sample missing")

                with col3:
                    try:
                        st.download_button(
                            "Web Developer Resume",
                            open("samples/web_dev_resume.pdf","rb"),
                            file_name="web_dev_resume.pdf"
                        )
                    except:
                        st.info("Sample missing")

                with col4:
                    try:
                        st.download_button(
                            "ML Engineer Resume",
                            open("samples/ml_engineer_resume.pdf","rb"),
                            file_name="ml_engineer_resume.pdf"
                        )
                    except:
                        st.info("Sample missing")


                st.markdown("---")


                st.subheader("📤 Upload Resume")

                uploaded_file = st.file_uploader(
                    "Upload your resume",
                    type=["pdf"]
                )


                if uploaded_file:

                    reader = PdfReader(uploaded_file)
                    text = ""
                    for page in reader.pages:
                        text += page.extract_text()
                    cleaned = clean_text(text)
                    # Extract skills
                    skills = extract_skills(cleaned)
                    # Detect domain using skills
                    domain, matched_skills = detect_domain(skills)

                    st.success("Resume analyzed successfully")

                    st.write("### 🎯 Detected Domain")

                    st.info(domain)

                    st.write("### 🛠 Extracted Skills")

                    st.write(skills)

                    st.write("### ✅ Skills matched with domain")

                    st.write(matched_skills)


        # =====================================================
        # TAB 2 : SKILL GAP
        # =====================================================

            with tab2:

                st.subheader("📊 Skill Gap Detection")

                if uploaded_file:

                    # ✅ Step 1: Detect domain
                    detected_domain, _ = detect_domain(skills)

                    # ✅ Step 2: Get ONLY domain-specific skills (MAIN FIX)
                    required_skills = domain_skills.get(detected_domain, [])

                    # ✅ Step 3: Skill gap analysis
                    missing_skills, matched_skills = detect_skill_gap(
                        skills,
                        required_skills
                    )

                    # ---------------- UI ----------------
                    st.write(f"### 🎯 Detected Domain: {detected_domain}")

                    st.write("### ❗ Missing Skills")
                    if missing_skills:
                        for skill in missing_skills:
                            st.warning(f"{skill}")
                    else:
                        st.success("No major skill gaps 🎉")

                    st.write("### 🚀 Suggestions")
                    for skill in missing_skills[:4]:
                        st.success(f"✔ Improve **{skill}** to strengthen your profile")


        # =====================================================
        # TAB 3 : CAREER PATH
        # =====================================================

            with tab3:

                st.subheader("🧭 Career Recommendation")

                if uploaded_file:
                    # 🔥 STEP 1: Detect domain (only for display)
                    detected_domain, _ = detect_domain(skills)
                    # 🔥 STEP 2: Get BEST ROLE (MAIN FIX)
                    from modules.roadmap_generator import get_best_role, generate_career_roadmap
                    best_role = get_best_role(skills)
                    # 🔥 STEP 3: Get skills for ONLY that role
                    required_skills = domain_skills.get(best_role, [])
                    # 🔥 STEP 4: Skill gap (ROLE BASED)
                    missing_skills, matched_skills = detect_skill_gap(
                        skills,
                        required_skills
                    )
                    # 🔥 STEP 5: Generate roadmap (ROLE BASED)
                    roadmap, _ = generate_career_roadmap(skills)
                    # ---------------- UI ----------------
                    st.write("### 🎯 Detected Domain")
                    st.success(detected_domain)
                    st.write("### 🎯 Best Matching Role")
                    st.success(best_role)
                    st.write("### ❗ Missing Skills")
                    if missing_skills:
                        for skill in missing_skills:
                            st.warning(skill)
                    else:
                        st.success("No major skill gaps 🎉")
                    st.write("### 🚀 Your Strengths")
                    for skill in matched_skills:
                        st.success(f"✔ {skill}")
                    # 🔥 BETTER SCORE
                    total = len(required_skills)
                    if total > 0:
                        score = int((len(matched_skills) / total) * 100)
                    else:
                        score = 65
                    st.write("### 📈 Resume Strength Score")
                    st.progress(score / 100)
                    st.metric("Resume Score", f"{score}/100")
                    # 🔥 ROADMAP
                    st.write("### 🗺 Learning Roadmap")
                    for month, task in roadmap:
                        st.write(f"{month}: {task}")
                else:
                    st.info("Upload resume first")

            st.markdown("---")

            st.markdown("## 📚 Career Preparation Resources")


            col1, col2, col3, col4 = st.columns(4)


            with col1:
                st.markdown("""
                <div style='background:linear-gradient(135deg,#667eea,#764ba2);
                padding:20px;border-radius:15px;color:white'>
                <h4>🧠 Aptitude</h4>
                <ul>
                <li><a href="https://www.indiabix.com/aptitude/" style="color:white">IndiaBix</a></li>
                <li><a href="https://prepinsta.com/aptitude/" style="color:white">PrepInsta</a></li>
                <li><a href="https://www.geeksforgeeks.org/aptitude-questions-and-answers/" style="color:white">GFG</a></li>
                </ul>
                </div>
                """, unsafe_allow_html=True)


            with col2:
                st.markdown("""
                <div style='background:linear-gradient(135deg,#f7971e,#ffd200);
                padding:20px;border-radius:15px;color:black'>
                <h4>💻 DSA</h4>
                <ul>
                <li><a href="https://leetcode.com" style="color:black">LeetCode</a></li>
                <li><a href="https://www.geeksforgeeks.org/data-structures/" style="color:black">GeeksforGeeks</a></li>
                <li><a href="https://takeuforward.org/" style="color:black">TakeUForward</a></li>
                </ul>
                </div>
                """, unsafe_allow_html=True)


            with col3:
                st.markdown("""
                <div style='background:linear-gradient(135deg,#11998e,#38ef7d);
                padding:20px;border-radius:15px;color:black'>
                <h4>🗣 Communication</h4>
                <ul>
                <li><a href="https://www.toastmasters.org/" style="color:black">Toastmasters</a></li>
                <li><a href="https://www.coursera.org/learn/english-for-career-development" style="color:black">Coursera</a></li>
                <li><a href="https://www.youtube.com/c/EnglishAddictwithMrSteve" style="color:black">YouTube</a></li>
                </ul>
                </div>
                """, unsafe_allow_html=True)


            with col4:
                st.markdown("""
                <div style='background:linear-gradient(135deg,#ff6a00,#ee0979);
                padding:20px;border-radius:15px;color:white'>
                <h4>🤖 AI / ML</h4>
                <ul>
                <li><a href="https://www.kaggle.com/learn" style="color:white">Kaggle</a></li>
                <li><a href="https://www.deeplearning.ai/" style="color:white">DeepLearning AI</a></li>
                <li><a href="https://www.coursera.org/learn/machine-learning" style="color:white">ML Coursera</a></li>
                </ul>
                </div>
                """, unsafe_allow_html=True)



        # =====================================================
        # TAB 4 : CHATBOT
        # =====================================================

            with tab4:

                st.subheader("💬 AI Career Assistant")

                init_chat(path_key, meta)

                handle_input(path_key)



# ===============================
# RIGHT SIDE : INFO PANEL
# ===============================

    with col_info:

        st.subheader("📢 Continuous Info")

        st.markdown('<div class="info-ticker-box">', unsafe_allow_html=True)

        updates = [
            "🔥 New IT Vacancies Released!",
            "📍 Top hiring partners 2026",
            "💡 Pro Tip: Update Resume Weekly",
            "🚀 AI Engineers demand increasing"
        ]

        for update in updates:
            st.markdown(f'<div class="ticker-item">{update}</div>', unsafe_allow_html=True)

        st.markdown('</div>', unsafe_allow_html=True)


# 3. SELECTION PAGE
elif st.session_state.page == 'select_type':
    if st.button("← Back to Home"):
        go_to('home')

    st.markdown(
        "<h1 style='text-align: center; margin-bottom:40px;'>Join NR Solution As</h1>",
        unsafe_allow_html=True
    )

    c1, c2, c3, c4 = st.columns(4)

    with c1:
        st.markdown('<div class="reg-card reg-student"><h1>🎓</h1><h3>Student</h3></div>', unsafe_allow_html=True)
        if st.button("Select Student", key="reg_std", use_container_width=True):
            go_to('form_student')

    with c2:
        st.markdown('<div class="reg-card reg-counselor"><h1>👨‍🏫</h1><h3>Counselor</h3></div>', unsafe_allow_html=True)
        if st.button("Select Counselor", key="reg_coun", use_container_width=True):
            go_to('form_counselor')

    with c3:
        st.markdown('<div class="reg-card reg-company"><h1>🏢</h1><h3>Company</h3></div>', unsafe_allow_html=True)
        if st.button("Select Company", key="reg_comp", use_container_width=True):
            go_to('form_company')

    with c4:
        st.markdown('<div class="reg-card reg-college"><h1>🏫</h1><h3>College</h3></div>', unsafe_allow_html=True)
        if st.button("Select College", key="reg_coll", use_container_width=True):
            go_to('form_college')


# 4. REGISTRATION FORMS
elif st.session_state.page.startswith('form_'):
    if st.button("← Back"):
        go_to('select_type')

    role = st.session_state.page.split('_')[1]
    st.markdown(f'<div class="form-container"><h2 style="text-align: center;">{role.upper()} REGISTRATION</h2></div>', unsafe_allow_html=True)

    _, form_col, _ = st.columns([1, 2.5, 1])
    with form_col:
        st.markdown(f'<div class="form-wrap-{role}">', unsafe_allow_html=True)

        with st.form("main_registration_form", clear_on_submit=True):
            if role == "student":
                st.text_input("Full Name")
                st.text_input("Email Address")
                st.text_input("Contact No")
                st.selectbox("Interested Sector", ["IT", "Govt Jobs", "Medical", "Study Abroad"])
            elif role == "college":
                st.text_input("College Name")
                st.multiselect("Departments", ["CS", "IT", "Mechanical", "Medical"])
                st.text_input("Website URL")
            elif role == "company":
                st.text_input("Company Name")
                st.text_area("Technical Stack")
                st.number_input("Open Vacancies", min_value=1)
            elif role == "counselor":
                st.text_input("Full Name")
                st.text_area("Expertise")
                st.slider("Years of Experience", 0, 30, 5)

            if st.form_submit_button("SUBMIT APPLICATION", use_container_width=True):
                st.success(f"Registration successful for {role}!")
                st.balloons()

        st.markdown('</div>', unsafe_allow_html=True)


# --- FOOTER ---
st.markdown("<br><hr><center>NR Solution © 2026</center>", unsafe_allow_html=True)